service: serverless-dice
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2

functions:
  diceroll:
    handler: handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
